src/Entity/Bono.php
<?php

namespace App\Entity;

use App\Repository\BonoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BonoRepository::class)]
class Bono
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10)]
    private ?string $Tipo = null;

    #[ORM\Column]
    private ?float $Precio = null;

    #[ORM\Column(nullable: true)]
    private ?int $DiasTotales = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $FechaCreacion = null;

    #[ORM\ManyToOne(inversedBy: 'bonos')]
    private ?Usuario $Usuario = null;

    #[ORM\OneToMany(mappedBy: 'Bono', targetEntity: DiaTachado::class)]
    private Collection $diaTachados;

    public function __construct()
    {
        $this->diaTachados = new ArrayCollection();
        $this->FechaCreacion = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipo(): ?string
    {
        return $this->Tipo;
    }

    public function setTipo(string $Tipo): static
    {
        $this->Tipo = $Tipo;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->Precio;
    }

    public function setPrecio(float $Precio): static
    {
        $this->Precio = $Precio;

        return $this;
    }

    public function getDiasTotales(): ?int
    {
        return $this->DiasTotales;
    }

    public function setDiasTotales(int $DiasTotales): static
    {
        $this->DiasTotales = ($this->Tipo === 'simple') ? 10 : 20;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->FechaCreacion;
    }

    public function setFechaCreacion(\DateTimeInterface $FechaCreacion): static
    {
        $this->FechaCreacion = $FechaCreacion;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->Usuario;
    }

    public function setUsuario(?Usuario $Usuario): static
    {
        $this->Usuario = $Usuario;

        return $this;
    }

    /**
     * @return Collection<int, DiaTachado>
     */
    public function getDiaTachados(): Collection
    {
        return $this->diaTachados;
    }

    public function addDiaTachado(DiaTachado $diaTachado): static
    {
        if (!$this->diaTachados->contains($diaTachado)) {
            $this->diaTachados->add($diaTachado);
            $diaTachado->setBono($this);
        }

        return $this;
    }

    public function removeDiaTachado(DiaTachado $diaTachado): static
    {
        if ($this->diaTachados->removeElement($diaTachado)) {
            // set the owning side to null (unless already changed)
            if ($diaTachado->getBono() === $this) {
                $diaTachado->setBono(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }
}

src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UsuarioRepository::class)]
class Usuario implements UserInterface, PasswordAuthenticatedUserInterface
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "El campo 'Correo' no puede estar vacío.")]
    #[Assert\Email()]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(length:500)]
    #[Assert\NotBlank(message: "El campo 'Contraseña' no puede estar vacío.")]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "El campo 'Nombre' no puede estar vacío.")]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "El campo 'Apellidos' no puede estar vacío.")]
    private ?string $Apellidos = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\NotBlank(message: "El campo 'DNI' no puede estar vacío.")]
    private ?string $DNI = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "El campo 'Edad' no puede estar vacío.")]
    #[Assert\GreaterThanOrEqual(value: 18, message: 'Este valor debe ser mayor o igual a 18')]
    private ?int $Edad = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $Sexo = null;

    #[ORM\OneToMany(mappedBy: 'Usuario', targetEntity: Bono::class)]
    private Collection $bonos;

    #[ORM\OneToMany(mappedBy: 'usuario', targetEntity: ReservaSpinning::class)]
    private Collection $ReservaSpinning;

    public function __construct()
    {
        $this->bonos = new ArrayCollection();
        $this->ReservaSpinning = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_CLIENTE';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
         //$this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->Apellidos;
    }

    public function setApellidos(string $Apellidos): static
    {
        $this->Apellidos = $Apellidos;

        return $this;
    }

    public function getDNI(): ?string
    {
        return $this->DNI;
    }

    public function setDNI(string $DNI): static
    {
        $this->DNI = $DNI;

        return $this;
    }

    public function getEdad(): ?int
    {
        return $this->Edad;
    }

    public function setEdad(int $Edad): static
    {
        $this->Edad = $Edad;

        return $this;
    }

    public function getSexo(): ?string
    {
        return $this->Sexo;
    }

    public function setSexo(?string $Sexo): static
    {
        $this->Sexo = $Sexo;

        return $this;
    }

    /**
     * @return Collection<int, Bono>
     */
    public function getBonos(): Collection
    {
        return $this->bonos;
    }

    public function addBono(Bono $bono): static
    {
        if (!$this->bonos->contains($bono)) {
            $this->bonos->add($bono);
            $bono->setUsuario($this);
        }

        return $this;
    }

    public function removeBono(Bono $bono): static
    {
        if ($this->bonos->removeElement($bono)) {
            // set the owning side to null (unless already changed)
            if ($bono->getUsuario() === $this) {
                $bono->setUsuario(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nombre . " " . $this->Apellidos;
    }

    /**
     * @return Collection<int, ReservaSpinning>
     */
    public function getReservaSpinning(): Collection
    {
        return $this->ReservaSpinning;
    }

    public function addReservaSpinning(ReservaSpinning $reservaSpinning): static
    {
        if (!$this->ReservaSpinning->contains($reservaSpinning)) {
            $this->ReservaSpinning->add($reservaSpinning);
            $reservaSpinning->setUsuario($this);
        }

        return $this;
    }

    public function removeReservaSpinning(ReservaSpinning $reservaSpinning): static
    {
        if ($this->ReservaSpinning->removeElement($reservaSpinning)) {
            // set the owning side to null (unless already changed)
            if ($reservaSpinning->getUsuario() === $this) {
                $reservaSpinning->setUsuario(null);
            }
        }

        return $this;
    }
}

src/Controller/BonoController.php
<?php

namespace App\Controller;

use App\Entity\Bono;
use App\Entity\DiaTachado;
use App\Repository\BonoRepository;
use App\Repository\UsuarioRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Serializer\Encoder\JsonDecode;

class BonoController extends AbstractController
{
    private $usuarioRepository;
    private $bonoRepository;

    public function __construct(UsuarioRepository $usuarioRepository, BonoRepository $bonoRepository)
    {
        $this->usuarioRepository = $usuarioRepository;
        $this->bonoRepository = $bonoRepository;
    }

    #[Route('/bono', name: 'app_bono')]
    public function index(): Response
    {
        return $this->render('bono/index.html.twig', [
            'controller_name' => 'BonoController',
        ]);
    }

    #[Route('/bono2', name: 'app_bono2')]
    public function mostrarBonoAction($idUsuario = 1)
    {
        // Obtener el usuario desde la base de datos
        $usuario = $this->usuarioRepository->find($idUsuario);

        // Verificar si el usuario existe
        if (!$usuario) {
            throw $this->createNotFoundException('Usuario no encontrado');
        }

        // Obtener el bono del usuario
        $bono = $usuario->getBonos()->first();

        // Renderizar la plantilla con los datos del bono
        return $this->render('bono/mostrarBono.html.twig', [
            'usuario' => $usuario,
            'bono' => $bono,
        ]);
    }

    #[Route('/bono3', name: 'app_bono3')]
    public function show(Security $security): Response
    {

        $user = $security->getUser();
        if ($user == null) {
            return $this->render('error/sinInicioDeSesion.html.twig', ['mensajeError' => 'Necesitas iniciar sesión para acceder a esta página.']);
        } else {
            $usuario = $this->usuarioRepository->find($user->getId());
            $bono = $usuario->getBonos()->last();
            return $this->render('bono/mostrarBono2.html.twig', [
                'bono' => $bono,
            ]);
        }
    }

    #[Route('/bono3/{id}', name: 'app_bono3_id')]
    public function bonoPorPersona($id): Response
    {
        $usuario = $this->usuarioRepository->find($id);
        $bono = $usuario->getBonos()->last();
        return $this->render('bono/mostrarBono2.html.twig', [
            'bono' => $bono,
        ]);
    }

    #[Route('/tacharDia', name: 'tachar_dia', methods: 'post')]
    public function tacharDia(Request $request, EntityManagerInterface $entityManager): Response
    {
        $data = json_decode($request->getContent(), true);

        $diaTachado = new DiaTachado();

        $diaTachado->setBono($this->bonoRepository->find($data['bonoId']));

        $entityManager->persist($diaTachado);
        $entityManager->flush();

        return new Response('Dia tachado correctamente con la id:' . $diaTachado->getId());
    }
}

templates/bono/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bono de Gimnasio
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('assets/js/bono.js') }}"></script>
{% endblock %}

{% block body %}
	<div class="container-bono">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				<div class="card">
					<div class="card-body">
						<div class="card-info">
							<img class="card-img-top" src="escudo_pueblo.png" alt="Escudo del pueblo">
							<h5 class="card-title">Cliente: Rafael Montoro</h5>
							<p class="card-subtitle">Polideportivo Municipal Lahiguera - Bono Musculación</p>
							<p class="card-text">Precio: 15€</p>
							<p class="card-days" id="days-left">Días Restantes: 10</p>
						</div>
						<div class="day-markers">
							<div class="day-marker" id="day-1"></div>
							<div class="day-marker" id="day-2"></div>
							<div class="day-marker" id="day-3"></div>
							<div class="day-marker" id="day-4"></div>
							<div class="day-marker" id="day-5"></div>
							<div class="day-marker" id="day-6"></div>
							<div class="day-marker" id="day-7"></div>
							<div class="day-marker" id="day-8"></div>
							<div class="day-marker" id="day-9"></div>
							<div class="day-marker" id="day-10"></div>
						</div>
					</div>
				</div>
				<div class="text-center">
					<button class="btn btn-primary mt-3" id="mark-day-btn">Marcar Día</button>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/bono/mostrarBono.html.twig
{% extends "base.html.twig" %}

{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('assets/js/mostrarBono.js') }}"></script>
{% endblock %}
{% block body %}
	<div class="container-mostrar-bono">
		<h1>Bono de
			{{ usuario.nombre }}
			{{ usuario.apellidos }}</h1>

		<div id="bonoInfo">
			<h2>Tipo de bono:
				{{ bono.tipo }}</h2>
			<p>Precio:
				{{ bono.precio }}</p>
			<p>Días totales:
				{{ bono.diasTotales }}</p>
		</div>
	</div>
{% endblock %}

templates/bono/mostrarBono2.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('assets/js/bono3.js') }}"></script>
{% endblock %}

{% block body %}
	<div class="container-mostrar-bono-2">
		<div class="card">
			<div class="card-header" id="{{bono.id}}">
				BONO
			</div>
			<div class="card-body d-flex flex-column align-items-center">
				{% if bono %}
					<h5 class="card-title text-center">POLIDEPORTIVO MUNICIPAL</h5>
					<h5 class="card-text text-center">LAHIGUERA</h5>
					<h2 class="card-text-t text-center">BONO MUSCULACION</h2>
					<div class="escudo-lahiguera">
						<img src="{{ asset('assets/images/EscudoLahiguera.svg.png') }}" alt="Escudo de Lahiguera">
					</div>
					<p class="card-text-usuario text-center">{{bono.Usuario.nombre}}
						{{bono.Usuario.apellidos}}</p>
					<p class="card-text text-center">Tipo de bono:
						{{ bono.Tipo }}</p>
					<p class="card-text text-center">Precio:
						{{ (bono.Precio / 100)|number_format(0, '.', '') }}€</p>
					<p class="card-text text-center">Días restantes:
						{{ bono.DiasTotales - bono.diaTachados|length }}</p>
					<div class="d-flex flex-wrap justify-content-center">
						{% set tachados = bono.diaTachados|length %}
						{% for i in 1..bono.DiasTotales %}
							<div class="cuadrado{% if loop.index <= tachados %} tachado{% endif %}">
								<span class="numero">{{ i }}</span>
							</div>
						{% endfor %}
					</div>
				{% else %}
					<p class="text-center">Actualmente no dispones de ningún bono</p>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}