src/Entity/Bicicleta.php
<?php

namespace App\Entity;

use App\Repository\BicicletaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BicicletaRepository::class)]
class Bicicleta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Estado = null;

    #[ORM\OneToMany(mappedBy: 'bicicleta', targetEntity: ReservaSpinning::class)]
    private Collection $ReservaSpinning;

    public function __construct()
    {
        $this->ReservaSpinning = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEstado(): ?string
    {
        return $this->Estado;
    }

    public function setEstado(string $Estado): static
    {
        $this->Estado = $Estado;

        return $this;
    }

    /**
     * @return Collection<int, ReservaSpinning>
     */
    public function getReservaSpinning(): Collection
    {
        return $this->ReservaSpinning;
    }

    public function addReservaSpinning(ReservaSpinning $reservaSpinning): static
    {
        if (!$this->ReservaSpinning->contains($reservaSpinning)) {
            $this->ReservaSpinning->add($reservaSpinning);
            $reservaSpinning->setBicicleta($this);
        }

        return $this;
    }

    public function removeReservaSpinning(ReservaSpinning $reservaSpinning): static
    {
        if ($this->ReservaSpinning->removeElement($reservaSpinning)) {
            // set the owning side to null (unless already changed)
            if ($reservaSpinning->getBicicleta() === $this) {
                $reservaSpinning->setBicicleta(null);
            }
        }

        return $this;
    }
}

src/Controller/SpinningController.php
<?php

namespace App\Controller;

use App\Entity\Bicicleta;
use App\Entity\ReservaSpinning;
use App\Repository\BicicletaRepository;
use App\Repository\ReservaSpinningRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class SpinningController extends AbstractController
{

    private $bicicletaRepository;
    private $reservaSpinningRepository;
    private $entityManager;

    public function __construct(BicicletaRepository $bicicletaRepository, ReservaSpinningRepository $reservaSpinningRepository, EntityManagerInterface $entityManager)
    {
        $this->bicicletaRepository = $bicicletaRepository;
        $this->reservaSpinningRepository = $reservaSpinningRepository;
        $this->entityManager = $entityManager;
    }

    #[Route('/spinning-reserva', name: 'app_spinning_reserva')]
    public function index(Security $security): Response
    {

        $user = $security->getUser();

        if ($user == null) {
            return $this->render('error/sinInicioDeSesion.html.twig', ['mensajeError' => 'Necesitas iniciar sesión para acceder a esta página.']);
        } else {
            $bicicletas = $this->bicicletaRepository->findAll();

            $queryBuilder = $this->entityManager->createQueryBuilder();

            $queryBuilder
                ->select('DISTINCT b')
                ->from('App\Entity\Bicicleta', 'b')
                ->innerJoin('App\Entity\ReservaSpinning', 'r', 'WITH', 'b.id = r.bicicleta')
                ->where($queryBuilder->expr()->eq('r.Fecha', 'CURRENT_DATE()'));

            $bicicletasReservadasHoy = $queryBuilder->getQuery()->getResult();

            return $this->render('spinning/index.html.twig', [
                'controller_name' => 'SpinningController',
                'bicicletas' => $bicicletas,
                'bicicletasConReserva' => $bicicletasReservadasHoy
            ]);
        }
    }


    /* #[Route('/crear_bicicletas', name: 'crear_bicicletas')]
    public function crearBicicletas(EntityManagerInterface $entityManager)
    {
        // Crear 16 bicicletas de prueba
        for ($i = 1; $i <= 16; $i++) {
            $bicicleta = new Bicicleta();
            $bicicleta->setDisponibilidad(true);
            $bicicleta->setEstado("Ready");
            
            $entityManager->persist($bicicleta);
        }
        
        $entityManager->flush();

        return $this->redirectToRoute('app_spinning');
    } */
}

templates/spinning/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reserva tu bici!
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('assets/js/spinning.js') }}"></script>
{% endblock %}

{% block body %}
	<div class="container container-spinning d-flex flex-column align-items-center">
		<h1 class="mb-4">Gestión de Reserva de Bicicletas de Spinning</h1>
		<div class="row">
      {% for bicicleta in bicicletas %}
        <div class="bike-icon">
    <i class="fas fa-bicycle {% if bicicleta.estado == 'Broken' %}broken{% elseif bicicleta in bicicletasConReserva %}reserved{% else %}available{% endif %}" data-id="{{ bicicleta.id }}"></i>
</div>
      {% endfor %}
    </div>

		<!-- Modal para mostrar mensajes -->
		<div id="modalMessage" class="modal modal-no-backdrop fade">
			<div
				class="modal-dialog modal-dialog-centered modal-lg">
				<!-- Agregamos la clase modal-dialog-centered para centrar el modal -->
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Mensaje</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<p id="modalText"></p>
					</div>
				</div>
			</div>
		</div>

		<!-- Modal para confirmar reserva -->
		<div id="modalConfirm" class="modal fade">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Confirmar reserva</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<p>¿Estás seguro de reservar esta bicicleta?</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" id="btnNo" data-dismiss="modal">No</button>
						<button type="button" class="btn btn-primary" id="btnReservar">Sí</button>
					</div>
				</div>
			</div>
		</div>


	</div>
{% endblock %}